### ISSUE TITLE
Error on `npx docusaurus generate-proto-docs` 

### ISSUE THREAD

**Issue by aesadde** [protobuffet/docusaurus-protobuffet#3]
Hi @AnthonyBobsin!

Project looks very cool, been trying to add it to my docusuarus wiki but haven't been able to.

I'm following the [instructions](https://protobuffet.com/docs/how/installation).

I have a generated `proto_workspace.json` in the `./fixtures` dir but when I run
`npx docusaurus generate-proto-docs`, I see the following error

```console
Error: The docs folder does not exist for version "current". A docs folder is expected to be found at protodocs.
    at checkVersionMetadataPaths (/Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/plugin-content-docs/lib/versions.js:233:15)
    at /Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/plugin-content-docs/lib/versions.js:309:51
    at Array.forEach (<anonymous>)
    at Object.readVersionsMetadata (/Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/plugin-content-docs/lib/versions.js:309:22)
    at Object.pluginContentDocs [as plugin] (/Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/plugin-content-docs/lib/index.js:28:41)
    at /Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:149:55
    at Array.map (<anonymous>)
    at Object.initPlugins [as default] (/Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:137:10)
    at externalCommand (/Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/core/lib/commands/external.js:15:35)
    at async run (/Users/aesadde/repos/akorda/docs/node_modules/@docusaurus/core/bin/docusaurus.js:245:5)
```

Is there anything I'm missing?

Thanks for the help

**Comment by aesadde** [comment]
It turns out that the plugin doesn't generate the directories and file it needs. They need to exist prior to running the tool.
