### ISSUE TITLE
Trouble with `docusaurus-protobuffet-init`

### ISSUE THREAD

**Issue by Breefield** [protobuffet/docusaurus-protobuffet#5]
npm version: `8.10.0`
node version: `v16.16.0`

I'm trying to run this inside a docker container:
```
/workspace # npx docusaurus-protobuffet-init init service
Triggering @docusaurus/core project creation.

Generation of base template from @docusaurus/init failed.
Error: Command failed: npx @docusaurus/init@latest init --use-npm service classic
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at /workspace/node_modules/docusaurus-protobuffet-init/dist/index.js:53:33
    at step (/workspace/node_modules/docusaurus-protobuffet-init/dist/index.js:34:23)
    at Object.next (/workspace/node_modules/docusaurus-protobuffet-init/dist/index.js:15:53)
    at /workspace/node_modules/docusaurus-protobuffet-init/dist/index.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/node_modules/docusaurus-protobuffet-init/dist/index.js:5:12)
    at init (/workspace/node_modules/docusaurus-protobuffet-init/dist/index.js:49:12)
```

Simply running `npx @docusaurus/init@latest init --use-npm service classic` works without issue.

**Comment by Breefield** [comment]
Ah it works when I'm the `root` user in the container, that'd do it.

**Comment by AnthonyBobsin** [comment]
Thank you for reporting, sorry for the delay. I will find time to dig into this within the next week.
